USE DATABASE F1_ANALYTICS;
USE SCHEMA BRONZE;

SELECT COUNT(*) AS ROW_COUNT
FROM F1_LAPS_RAW;

SELECT
    COUNT_IF(RACEYEAR IS NULL) AS NULL_RACEYEAR,
    COUNT_IF(GRANDPRIX IS NULL) AS NULL_GRANDPRIX,
    COUNT_IF(SESSIONTYPE IS NULL) AS NULL_SESSIONTYPE,
    COUNT_IF(DRIVER IS NULL) AS NULL_DRIVER,
    COUNT_IF(LAPNUMBER IS NULL) AS NULL_LAPNUMBER,
    COUNT_IF(LAPTIME IS NULL) AS NULL_LAPTIME,
    COUNT_IF(COMPOUND IS NULL) AS NULL_COMPOUND,
    COUNT_IF(STINT IS NULL) AS NULL_STINT
FROM F1_LAPS_RAW;

SELECT *
FROM F1_LAPS_RAW
WHERE LAPNUMBER <= 0
   OR LAPTIME <= 0
   OR STINT < 0;

SELECT
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    DRIVER,
    LAPNUMBER,
    COUNT(*) AS DUP_COUNT
FROM F1_LAPS_RAW
GROUP BY 1,2,3,4,5
HAVING COUNT(*) > 1;