USE DATABASE F1_ANALYTICS;
USE SCHEMA SILVER;

SELECT COUNT(*) AS ROW_COUNT
FROM F1_LAPS_CLEAN;

SELECT
    COUNT_IF(LAPTIME IS NULL) AS NULL_LAPTIME,
    COUNT_IF(LAPTIME <= 0) AS INVALID_LAPTIME,
    COUNT_IF(LAPNUMBER <= 0) AS INVALID_LAPNUMBER
FROM F1_LAPS_CLEAN;