USE DATABASE F1_ANALYTICS;
USE SCHEMA GOLD;

SELECT COUNT(*) AS ROW_COUNT
FROM F1_TYRE_STRATEGY;

SELECT *
FROM F1_TYRE_STRATEGY
WHERE STINT_LENGTH <= 0
   OR AVG_LAPTIME <= 0;

SELECT COUNT(*) AS ROW_COUNT
FROM F1_DRIVER_PERFORMANCE;

SELECT COUNT(*) AS ROW_COUNT
FROM F1_RACE_SUMMARY;