SELECT
    COMPOUND,
    AVG_LAPTIME
FROM F1_ANALYTICS.GOLD.F1_RACE_SUMMARY
ORDER BY AVG_LAPTIME ASC;

SELECT
    DRIVER,
    AVG_LAPTIME,
    LAPTIME_STDDEV
FROM F1_ANALYTICS.GOLD.F1_DRIVER_PERFORMANCE
ORDER BY LAPTIME_STDDEV ASC;

SELECT
    DRIVER,
    COMPOUND,
    STINT,
    STINT_LENGTH,
    AVG_LAPTIME,
    LAP_TIME_RANGE
FROM F1_ANALYTICS.GOLD.F1_TYRE_STRATEGY
ORDER BY STINT_LENGTH DESC, AVG_LAPTIME ASC;