USE DATABASE F1_ANALYTICS;
USE SCHEMA GOLD;

SELECT
    RACEYEAR,
    GRANDPRIX,
    COMPOUND,
    AVG_LAPTIME
FROM F1_RACE_SUMMARY
ORDER BY RACEYEAR, GRANDPRIX, AVG_LAPTIME ASC;

SELECT
    RACEYEAR,
    GRANDPRIX,
    DRIVER,
    AVG_LAPTIME,
    LAPTIME_STDDEV
FROM F1_DRIVER_PERFORMANCE
ORDER BY RACEYEAR, GRANDPRIX, LAPTIME_STDDEV ASC;

SELECT
    RACEYEAR,
    GRANDPRIX,
    DRIVER,
    COMPOUND,
    STINT,
    STINT_LENGTH,
    AVG_LAPTIME,
    LAP_TIME_RANGE
FROM F1_TYRE_STRATEGY
ORDER BY RACEYEAR, GRANDPRIX, STINT_LENGTH DESC, AVG_LAPTIME ASC;