USE DATABASE F1_ANALYTICS;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE F1_LAPS_CLEAN AS
SELECT
    DRIVER,
    LAPNUMBER,
    CAST(LAPTIME AS FLOAT) AS LAPTIME,
    COMPOUND,
    STINT
FROM F1_ANALYTICS.BRONZE.F1_LAPS_RAW
WHERE LAPTIME IS NOT NULL;

SELECT * FROM F1_LAPS_CLEAN LIMIT 10;