USE DATABASE F1_ANALYTICS;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE F1_LAPS_CLEAN AS
SELECT
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    DRIVER,
    LAPNUMBER,
    CAST(LAPTIME AS FLOAT) AS LAPTIME,
    COMPOUND,
    STINT,
    LOAD_TS
FROM F1_ANALYTICS.BRONZE.F1_LAPS_RAW
WHERE LAPTIME IS NOT NULL
  AND LAPTIME > 0
  AND LAPNUMBER > 0;