CREATE OR REPLACE TABLE F1_LAPS_FEATURES AS
SELECT
    DRIVER,
    COMPOUND,
    STINT,
    COUNT(*) AS STINT_LENGTH,
    AVG(LAPTIME) AS AVG_LAPTIME,
    MIN(LAPTIME) AS BEST_LAP,
    MAX(LAPTIME) AS WORST_LAP
FROM F1_LAPS_CLEAN
GROUP BY DRIVER, COMPOUND, STINT;

SELECT * FROM F1_LAPS_FEATURES LIMIT 10;