USE DATABASE F1_ANALYTICS;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE F1_LAPS_FEATURES AS
SELECT
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    DRIVER,
    COMPOUND,
    STINT,
    COUNT(*) AS STINT_LENGTH,
    AVG(LAPTIME) AS AVG_LAPTIME,
    MIN(LAPTIME) AS BEST_LAP,
    MAX(LAPTIME) AS WORST_LAP
FROM F1_ANALYTICS.SILVER.F1_LAPS_CLEAN
GROUP BY
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    DRIVER,
    COMPOUND,
    STINT;