USE DATABASE F1_ANALYTICS;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE F1_TYRE_STRATEGY AS
SELECT
    DRIVER,
    COMPOUND,
    STINT,
    STINT_LENGTH,
    AVG_LAPTIME,
    BEST_LAP,
    WORST_LAP,
    WORST_LAP - BEST_LAP AS LAP_TIME_RANGE
FROM F1_ANALYTICS.SILVER.F1_LAPS_FEATURES;

SELECT * FROM F1_TYRE_STRATEGY LIMIT 10;