CREATE OR REPLACE TABLE F1_DRIVER_PERFORMANCE AS
SELECT
    DRIVER,
    COUNT(*) AS TOTAL_LAPS,
    AVG(LAPTIME) AS AVG_LAPTIME,
    MIN(LAPTIME) AS BEST_LAP,
    MAX(LAPTIME) AS WORST_LAP,
    STDDEV(LAPTIME) AS LAPTIME_STDDEV
FROM F1_ANALYTICS.SILVER.F1_LAPS_CLEAN
GROUP BY DRIVER;

SELECT * FROM F1_DRIVER_PERFORMANCE LIMIT 10;