USE DATABASE F1_ANALYTICS;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE F1_RACE_SUMMARY AS
SELECT
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    COMPOUND,
    COUNT(*) AS TOTAL_LAPS,
    AVG(LAPTIME) AS AVG_LAPTIME,
    MIN(LAPTIME) AS BEST_LAP,
    MAX(LAPTIME) AS WORST_LAP
FROM F1_ANALYTICS.SILVER.F1_LAPS_CLEAN
GROUP BY
    RACEYEAR,
    GRANDPRIX,
    SESSIONTYPE,
    COMPOUND;