USE DATABASE F1_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE F1_LAPS_RAW (
    Driver STRING,
    LapNumber INT,
    LapTime FLOAT,
    Compound STRING,
    Stint INT
);

SELECT * FROM F1_ANALYTICS.BRONZE.F1_LAPS_RAW LIMIT 10;