USE DATABASE F1_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE F1_LAPS_RAW (
    RACEYEAR INT,
    GRANDPRIX STRING,
    SESSIONTYPE STRING,
    DRIVER STRING,
    LAPNUMBER INT,
    LAPTIME FLOAT,
    COMPOUND STRING,
    STINT INT,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);