USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS F1_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE F1_WH;

CREATE DATABASE IF NOT EXISTS F1_ANALYTICS;
USE DATABASE F1_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS F1_LAPS_RAW (
    RACEYEAR INT,
    GRANDPRIX STRING,
    SESSIONTYPE STRING,
    DRIVER STRING,
    LAPNUMBER INT,
    LAPTIME FLOAT,
    COMPOUND STRING,
    STINT INT
);