SELECT CURRENT_ROLE();
SELECT CURRENT_USER();

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS F1_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE F1_WH;

CREATE DATABASE IF NOT EXISTS F1_ANALYTICS;
USE DATABASE F1_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE F1_ANALYTICS;